/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SRestoreProfile
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var PLUGINS_INDEX_URL = "https://raw.githubusercontent.com/obsidianmd/obsidian-releases/master/community-plugins.json";
var THEMES_INDEX_URL = "https://raw.githubusercontent.com/obsidianmd/obsidian-releases/master/community-css-themes.json";
async function fetchIndex(type) {
  const url = type === "plugins" ? PLUGINS_INDEX_URL : THEMES_INDEX_URL;
  const res = await (0, import_obsidian.requestUrl)({ url });
  return res.json;
}
async function getLatestTagInfo(repo) {
  for (const branch of ["master", "main"]) {
    try {
      const res = await (0, import_obsidian.requestUrl)({
        url: `https://raw.githubusercontent.com/${repo}/${branch}/manifest.json`,
        throw: false
      });
      if (res.status === 200) {
        const data = res.json;
        if (!data.version) continue;
        return { tag: data.version, branch };
      }
    } catch (e) {
      continue;
    }
  }
  return null;
}
async function fetchFileBuffer(url) {
  try {
    const res = await (0, import_obsidian.requestUrl)({ url, throw: false });
    if (res.status === 200) return res.arrayBuffer;
    return null;
  } catch (e) {
    return null;
  }
}
async function installItem(type, idOrName, repo, vault, logFn) {
  const dir = (0, import_obsidian.normalizePath)(`${vault.configDir}/${type}/${idOrName}`);
  const saveToDisk = async (buffers) => {
    const dirExists = await vault.adapter.exists(dir);
    if (!dirExists) await vault.createFolder(dir);
    for (const [filename, buffer] of Object.entries(buffers)) {
      await vault.adapter.writeBinary((0, import_obsidian.normalizePath)(`${dir}/${filename}`), buffer);
    }
  };
  logFn(`  Fetching latest version...`);
  const tagInfo = await getLatestTagInfo(repo);
  const tag = tagInfo == null ? void 0 : tagInfo.tag;
  const branch = tagInfo == null ? void 0 : tagInfo.branch;
  if (tag) {
    logFn(`  Version: ${tag}`);
    const base = `https://github.com/${repo}/releases/download/${tag}`;
    let ok = true;
    const buffers = {};
    const filesToDownload = type === "plugins" ? ["main.js", "manifest.json"] : ["theme.css", "manifest.json"];
    for (const file of filesToDownload) {
      logFn(`  Downloading ${file}...`);
      const buf = await fetchFileBuffer(`${base}/${file}`);
      if (!buf) {
        logFn(`  \u2717 Failed: ${file}`);
        ok = false;
        break;
      } else {
        buffers[file] = buf;
        logFn(`  \u2713 ${file}`);
      }
    }
    if (ok) {
      if (type === "plugins") {
        const stylesBuf = await fetchFileBuffer(`${base}/styles.css`);
        if (stylesBuf) buffers["styles.css"] = stylesBuf;
      }
      await saveToDisk(buffers);
      return { success: true, method: "direct" };
    }
  }
  logFn(`  Trying via GitHub API...`);
  try {
    const res = await (0, import_obsidian.requestUrl)({
      url: `https://api.github.com/repos/${repo}/releases`,
      throw: false
    });
    if (res.status !== 200) throw new Error("API unavailable");
    const releases = res.json;
    if (!Array.isArray(releases) || !releases.length)
      throw new Error("No releases found");
    const requiredAssets = type === "plugins" ? ["main.js", "manifest.json"] : ["theme.css", "manifest.json"];
    const allAssets = type === "plugins" ? ["main.js", "manifest.json", "styles.css"] : requiredAssets;
    const assets = releases[0].assets.filter(
      (a) => allAssets.includes(a.name)
    );
    let ok = true;
    const buffers = {};
    for (const asset of assets) {
      logFn(`  Downloading ${asset.name} (API)...`);
      const buf = await fetchFileBuffer(asset.browser_download_url);
      if (!buf && requiredAssets.includes(asset.name)) {
        logFn(`  \u2717 Failed: ${asset.name}`);
        ok = false;
        break;
      } else if (buf) {
        buffers[asset.name] = buf;
        logFn(`  \u2713 ${asset.name}`);
      }
    }
    if (ok && requiredAssets.every((ra) => assets.some((a) => a.name === ra && buffers[ra]))) {
      await saveToDisk(buffers);
      return { success: true, method: "api" };
    }
  } catch (e) {
    logFn(`  \u2717 API: ${e.message}`);
  }
  if (branch) {
    logFn(`  Trying raw files from ${branch} branch...`);
    const rawBase = `https://raw.githubusercontent.com/${repo}/${branch}`;
    let rawOk = true;
    const buffers = {};
    const filesToDownload = type === "plugins" ? ["main.js", "manifest.json"] : ["theme.css", "manifest.json"];
    for (const file of filesToDownload) {
      logFn(`  Downloading ${file} (raw)...`);
      const buf = await fetchFileBuffer(`${rawBase}/${file}`);
      if (!buf) {
        logFn(`  \u2717 Failed: ${file}`);
        rawOk = false;
        break;
      } else {
        buffers[file] = buf;
        logFn(`  \u2713 ${file}`);
      }
    }
    if (rawOk) {
      if (type === "plugins") {
        const stylesBuf = await fetchFileBuffer(`${rawBase}/styles.css`);
        if (stylesBuf) buffers["styles.css"] = stylesBuf;
      }
      await saveToDisk(buffers);
      return { success: true, method: "raw" };
    }
  }
  return { success: false };
}
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, message, onConfirm) {
    super(app);
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "Confirm Action" });
    contentEl.createEl("p", { text: this.message });
    const footer = contentEl.createDiv({ cls: "s-restore-profile-footer" });
    footer.setCssStyles({ marginTop: "20px" });
    const btnConfirm = footer.createEl("button", {
      text: "Yes",
      cls: "mod-cta s-restore-profile-btn-danger"
    });
    btnConfirm.onclick = () => {
      this.onConfirm();
      this.close();
    };
    const btnCancel = footer.createEl("button", { text: "Cancel" });
    btnCancel.onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ReinstallerModal = class extends import_obsidian.Modal {
  constructor(app) {
    super(app);
    this.pluginIndex = null;
    this.themeIndex = null;
    this.profilePlugins = [];
    this.profileThemes = [];
    this.checkedPlugins = {};
    this.checkedThemes = {};
    this.currentTab = "plugins";
    this.installing = false;
    this.log = [];
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("s-restore-profile-modal");
    this.modalEl.addClass("s-restore-profile-window");
    contentEl.createEl("h2", { text: "S-Restore Profile" });
    try {
      this.pluginIndex = await fetchIndex("plugins");
    } catch (e) {
    }
    try {
      this.themeIndex = await fetchIndex("themes");
    } catch (e) {
    }
    let activePlugins = [];
    try {
      const raw = await this.app.vault.adapter.read(
        (0, import_obsidian.normalizePath)(this.app.vault.configDir + "/community-plugins.json")
      );
      activePlugins = JSON.parse(raw);
    } catch (e) {
    }
    let activeTheme = "";
    try {
      const raw = await this.app.vault.adapter.read(
        (0, import_obsidian.normalizePath)(this.app.vault.configDir + "/appearance.json")
      );
      const appearanceData = JSON.parse(raw);
      activeTheme = appearanceData.cssTheme || "";
    } catch (e) {
    }
    try {
      const pluginDirList = await this.app.vault.adapter.list((0, import_obsidian.normalizePath)(this.app.vault.configDir + "/plugins"));
      for (const folder of pluginDirList.folders) {
        try {
          const manifestRaw = await this.app.vault.adapter.read(`${folder}/manifest.json`);
          const manifest = JSON.parse(manifestRaw);
          if (manifest.id === "s-restore-profile") continue;
          this.profilePlugins.push({
            id: manifest.id,
            name: manifest.name,
            version: manifest.version,
            description: manifest.description,
            author: manifest.author,
            enabled: activePlugins.includes(manifest.id)
          });
        } catch (e) {
        }
      }
    } catch (e) {
    }
    try {
      const themeDirList = await this.app.vault.adapter.list((0, import_obsidian.normalizePath)(this.app.vault.configDir + "/themes"));
      for (const folder of themeDirList.folders) {
        try {
          const manifestRaw = await this.app.vault.adapter.read(`${folder}/manifest.json`);
          const manifest = JSON.parse(manifestRaw);
          this.profileThemes.push({
            name: manifest.name,
            version: manifest.version,
            author: manifest.author,
            active: activeTheme === manifest.name
          });
        } catch (e) {
        }
      }
    } catch (e) {
    }
    for (const p of this.profilePlugins) {
      const isInstalled = await this.app.vault.adapter.exists((0, import_obsidian.normalizePath)(`${this.app.vault.configDir}/plugins/${p.id}/main.js`));
      this.checkedPlugins[p.id] = !isInstalled;
    }
    for (const t of this.profileThemes) {
      const isInstalled = await this.app.vault.adapter.exists((0, import_obsidian.normalizePath)(`${this.app.vault.configDir}/themes/${t.name}/theme.css`));
      this.checkedThemes[t.name] = !isInstalled;
    }
    this.renderList(contentEl);
  }
  renderList(contentEl) {
    const tabsContainer = contentEl.createDiv({ cls: "s-restore-profile-tabs" });
    tabsContainer.setCssStyles({
      display: "flex",
      gap: "10px",
      marginBottom: "10px",
      borderBottom: "1px solid var(--background-modifier-border)"
    });
    const btnTabPlugins = tabsContainer.createEl("button", { text: "Plugins" });
    const btnTabThemes = tabsContainer.createEl("button", { text: "Themes" });
    btnTabPlugins.setCssStyles({
      background: this.currentTab === "plugins" ? "var(--interactive-accent)" : "transparent",
      borderBottom: "none"
    });
    btnTabThemes.setCssStyles({
      background: this.currentTab === "themes" ? "var(--interactive-accent)" : "transparent",
      borderBottom: "none"
    });
    btnTabPlugins.onclick = () => {
      this.currentTab = "plugins";
      this.refreshUI();
    };
    btnTabThemes.onclick = () => {
      this.currentTab = "themes";
      this.refreshUI();
    };
    const isPlugins = this.currentTab === "plugins";
    const currentList = isPlugins ? this.profilePlugins : this.profileThemes;
    const currentChecked = isPlugins ? this.checkedPlugins : this.checkedThemes;
    const sub = contentEl.createEl("p", { cls: "s-restore-profile-sub" });
    sub.setText(`${currentList.length} ${isPlugins ? "plugin(s)" : "theme(s)"} found in current list:`);
    const actions = contentEl.createDiv({ cls: "s-restore-profile-actions" });
    actions.setCssStyles({
      display: "flex",
      justifyContent: "space-between"
    });
    const leftActions = actions.createDiv({ cls: "s-restore-profile-actions-left" });
    leftActions.setCssStyles({
      display: "flex",
      gap: "8px"
    });
    const btnAll = leftActions.createEl("button", { text: `Select all` });
    btnAll.onclick = () => {
      currentList.forEach((item) => {
        const idOrName = isPlugins ? item.id : item.name;
        currentChecked[idOrName] = true;
        const cb = contentEl.querySelector(`[data-id="${idOrName}"]`);
        if (cb) cb.checked = true;
      });
      this.updateSelectionCount();
    };
    const btnNone = leftActions.createEl("button", { text: `Deselect all` });
    btnNone.onclick = () => {
      currentList.forEach((item) => {
        const idOrName = isPlugins ? item.id : item.name;
        currentChecked[idOrName] = false;
        const cb = contentEl.querySelector(`[data-id="${idOrName}"]`);
        if (cb) cb.checked = false;
      });
      this.updateSelectionCount();
    };
    const rightActions = actions.createDiv({ cls: "s-restore-profile-actions-right" });
    rightActions.setCssStyles({
      display: "flex",
      gap: "8px"
    });
    const btnGenerate = rightActions.createEl("button", { text: "Generate Profile Data" });
    btnGenerate.onclick = () => this.generateProfileData();
    const btnLoad = rightActions.createEl("button", { text: "Load Profile Data" });
    btnLoad.onclick = () => this.loadProfileData();
    const list = contentEl.createDiv({ cls: "s-restore-profile-list" });
    currentList.forEach((item) => {
      const isP = isPlugins;
      const p = item;
      const t = item;
      const idOrName = isP ? p.id : t.name;
      const name = isP ? p.name : t.name;
      const version = isP ? p.version : t.version;
      const row = list.createDiv({ cls: "s-restore-profile-item" });
      const label = row.createEl("label");
      const cb = label.createEl("input", { type: "checkbox" });
      cb.checked = currentChecked[idOrName];
      cb.dataset.id = idOrName;
      cb.onchange = async () => {
        currentChecked[idOrName] = cb.checked;
        this.updateSelectionCount();
        if (cb.checked) {
          const exists2 = await this.app.vault.adapter.exists(
            (0, import_obsidian.normalizePath)(`${this.app.vault.configDir}/${isP ? "plugins" : "themes"}/${idOrName}/${isP ? "main.js" : "theme.css"}`)
          );
          if (exists2) {
            new import_obsidian.Notice(`${isP ? "Plugin" : "Theme"} already installed: ${name}`);
          }
        }
      };
      const versionText = version ? `v${version}` : "No Release version";
      label.createSpan({ text: `${name} (${versionText})`, cls: "s-restore-profile-id" });
      const exists = this.app.vault.adapter.exists(
        (0, import_obsidian.normalizePath)(`${this.app.vault.configDir}/${isP ? "plugins" : "themes"}/${idOrName}/${isP ? "main.js" : "theme.css"}`)
      );
      void exists.then(async (e) => {
        if (e) {
          let badgeText = "  |  Installed \u2714\uFE0E";
          if (!isP && t.active) {
            badgeText = "  |  Active  |  Installed \u2714\uFE0E";
          }
          row.createSpan({
            text: badgeText,
            cls: "s-restore-profile-badge"
          });
        } else {
          const index = isP ? this.pluginIndex : this.themeIndex;
          if (index) {
            const inIndex = isP ? index.some((i) => i.id === idOrName) : index.some((i) => i.name === idOrName);
            if (!inIndex) {
              const errSpan = row.createSpan({
                text: "  |  Not found in index",
                cls: "s-restore-profile-error"
              });
              errSpan.setCssStyles({ fontSize: "var(--font-ui-smaller)" });
            }
          }
        }
      });
    });
    this.logEl = contentEl.createDiv({ cls: "s-restore-profile-log" });
    this.logEl.setCssStyles({ display: "none" });
    const footer = contentEl.createDiv({ cls: "s-restore-profile-footer" });
    footer.setCssStyles({
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: "20px"
    });
    this.selectedCountLabel = footer.createDiv({ cls: "s-restore-profile-count" });
    this.selectedCountLabel.setCssStyles({
      display: "flex",
      flexDirection: "column",
      fontSize: "var(--font-ui-smaller)",
      color: "var(--text-muted)"
    });
    this.updateSelectionCount();
    const rightFooter = footer.createDiv();
    rightFooter.setCssStyles({
      display: "flex",
      gap: "8px"
    });
    this.btnConfirm = rightFooter.createEl("button", {
      text: "Reinstall selected",
      cls: "mod-cta"
    });
    this.btnConfirm.onclick = () => this.runInstall();
    this.btnUninstall = rightFooter.createEl("button", {
      text: "Uninstall selected",
      cls: "s-restore-profile-btn-danger"
    });
    this.btnUninstall.onclick = () => this.runUninstall();
    const btnClose = rightFooter.createEl("button", { text: "Close" });
    btnClose.onclick = () => this.close();
  }
  updateSelectionCount() {
    const pCount = this.profilePlugins.filter((p) => this.checkedPlugins[p.id]).length;
    const tCount = this.profileThemes.filter((t) => this.checkedThemes[t.name]).length;
    if (this.selectedCountLabel) {
      this.selectedCountLabel.empty();
      this.selectedCountLabel.createDiv({ text: `Plugins: ${pCount}` });
      this.selectedCountLabel.createDiv({ text: `Themes: ${tCount}` });
    }
  }
  appendLog(msg) {
    this.log.push(msg);
    const line = this.logEl.createEl("div", { text: msg });
    line.scrollIntoView({ block: "end" });
  }
  async generateProfileData() {
    const selectedPlugins = this.profilePlugins.filter((p) => this.checkedPlugins[p.id]);
    const selectedThemes = this.profileThemes.filter((t) => this.checkedThemes[t.name]);
    if (!selectedPlugins.length && !selectedThemes.length) {
      new import_obsidian.Notice("No items selected to generate data.");
      return;
    }
    new import_obsidian.Notice("Generating Profile Data...");
    try {
      const pIndex = await fetchIndex("plugins");
      const pRepoMap = {};
      pIndex.forEach((i) => {
        if (i.id) pRepoMap[i.id] = i.repo;
      });
      const tIndex = await fetchIndex("themes");
      const tRepoMap = {};
      tIndex.forEach((i) => tRepoMap[i.name] = i.repo);
      const exportData = {
        plugins: selectedPlugins.map((p) => ({ ...p, repo: pRepoMap[p.id] || p.repo })),
        themes: selectedThemes.map((t) => ({ ...t, repo: tRepoMap[t.name] || t.repo }))
      };
      const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = activeDocument.createElement("a");
      a.href = url;
      a.download = "s-restore-profile-data.json";
      activeDocument.body.appendChild(a);
      a.click();
      activeDocument.body.removeChild(a);
      URL.revokeObjectURL(url);
      new import_obsidian.Notice("Profile Data Generated!");
    } catch (e) {
      new import_obsidian.Notice("Failed to generate Profile Data.");
      console.error(e);
    }
  }
  loadProfileData() {
    const input = activeDocument.createElement("input");
    input.type = "file";
    input.accept = ".json";
    input.onchange = (e) => {
      var _a;
      const file = (_a = e.target.files) == null ? void 0 : _a[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = (ev) => {
        var _a2;
        try {
          const data = JSON.parse((_a2 = ev.target) == null ? void 0 : _a2.result);
          if (Array.isArray(data)) {
            this.profilePlugins = data;
            this.profileThemes = [];
          } else {
            this.profilePlugins = data.plugins || [];
            this.profileThemes = data.themes || [];
          }
          this.checkedPlugins = {};
          this.checkedThemes = {};
          this.profilePlugins.forEach((p) => this.checkedPlugins[p.id] = true);
          this.profileThemes.forEach((t) => this.checkedThemes[t.name] = true);
          this.refreshUI();
          new import_obsidian.Notice("Profile Data Loaded!");
        } catch (e2) {
          new import_obsidian.Notice("Failed to parse JSON.");
        }
      };
      reader.readAsText(file);
    };
    input.click();
  }
  async runInstall() {
    if (this.installing) return;
    const selectedPlugins = this.profilePlugins.filter((p) => this.checkedPlugins[p.id]);
    const selectedThemes = this.profileThemes.filter((t) => this.checkedThemes[t.name]);
    if (!selectedPlugins.length && !selectedThemes.length) {
      new import_obsidian.Notice("No items selected.");
      return;
    }
    this.installing = true;
    this.btnConfirm.disabled = true;
    this.btnConfirm.setText("Installing...");
    this.logEl.setCssStyles({ display: "block" });
    this.logEl.empty();
    let success = 0, skip = 0, fail = 0;
    if (selectedPlugins.length > 0) {
      this.appendLog("\u{1F4E5} Fetching plugin index...");
      let index = [];
      try {
        index = await fetchIndex("plugins");
      } catch (e) {
        this.appendLog("\u274C Failed to fetch plugin index.");
        this.installing = false;
        this.btnConfirm.disabled = false;
        this.btnConfirm.setText("Reinstall selected");
        return;
      }
      const repoMap = {};
      index.forEach((p) => {
        if (p.id) repoMap[p.id] = p.repo;
      });
      for (const p of selectedPlugins) {
        const id = p.id;
        this.appendLog(`
\u2500\u2500 [Plugin] ${p.name}`);
        const alreadyInstalled = await this.app.vault.adapter.exists((0, import_obsidian.normalizePath)(`${this.app.vault.configDir}/plugins/${id}/main.js`));
        if (alreadyInstalled) {
          this.appendLog(`  \u23ED Already installed, skipping.`);
          skip++;
          continue;
        }
        const repo = p.repo || repoMap[id];
        if (!repo) {
          this.appendLog(`  \u26A0\uFE0F Not found in the official index.`);
          fail++;
          continue;
        }
        const result = await installItem("plugins", id, repo, this.app.vault, (msg) => this.appendLog(msg));
        if (result.success) {
          this.appendLog(`  \u2705 Installed (${result.method})`);
          if (p.enabled) {
            const cpPath = (0, import_obsidian.normalizePath)(this.app.vault.configDir + "/community-plugins.json");
            let cpList = [];
            try {
              const cpRaw = await this.app.vault.adapter.read(cpPath);
              cpList = JSON.parse(cpRaw);
            } catch (e) {
            }
            if (!cpList.includes(id)) {
              cpList.push(id);
              await this.app.vault.adapter.write(cpPath, JSON.stringify(cpList, null, 2));
              this.appendLog(`  \u2705 Enabled`);
            }
          }
          success++;
        } else {
          this.appendLog(`  \u274C Installation failed.`);
          fail++;
        }
      }
    }
    if (selectedThemes.length > 0) {
      this.appendLog("\n\u{1F4E5} Fetching theme index...");
      let index = [];
      try {
        index = await fetchIndex("themes");
      } catch (e) {
        this.appendLog("\u274C Failed to fetch theme index.");
      }
      const repoMap = {};
      index.forEach((t) => repoMap[t.name] = t.repo);
      for (const t of selectedThemes) {
        const name = t.name;
        this.appendLog(`
\u2500\u2500 [Theme] ${name}`);
        const alreadyInstalled = await this.app.vault.adapter.exists((0, import_obsidian.normalizePath)(`${this.app.vault.configDir}/themes/${name}/theme.css`));
        if (alreadyInstalled) {
          this.appendLog(`  \u23ED Already installed, skipping.`);
          skip++;
          continue;
        }
        const repo = t.repo || repoMap[name];
        if (!repo) {
          this.appendLog(`  \u26A0\uFE0F Not found in the official index.`);
          fail++;
          continue;
        }
        const result = await installItem("themes", name, repo, this.app.vault, (msg) => this.appendLog(msg));
        if (result.success) {
          this.appendLog(`  \u2705 Installed (${result.method})`);
          if (t.active) {
            const apPath = (0, import_obsidian.normalizePath)(this.app.vault.configDir + "/appearance.json");
            let apData = {};
            try {
              const apRaw = await this.app.vault.adapter.read(apPath);
              apData = JSON.parse(apRaw);
            } catch (e) {
            }
            apData.cssTheme = name;
            await this.app.vault.adapter.write(apPath, JSON.stringify(apData, null, 2));
            this.appendLog(`  \u2705 Set as active theme`);
          }
          success++;
        } else {
          this.appendLog(`  \u274C Installation failed.`);
          fail++;
        }
      }
    }
    this.appendLog(`
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550`);
    this.appendLog(`\u2705 Installed : ${success}`);
    this.appendLog(`\u23ED Skipped   : ${skip}`);
    this.appendLog(`\u274C Failed    : ${fail}`);
    this.appendLog(`
Restart Obsidian to activate the installed plugins/themes.`);
    this.installing = false;
    this.btnConfirm.disabled = false;
    this.btnConfirm.setText("Reinstall selected");
  }
  async runUninstall() {
    if (this.installing) return;
    const selectedPlugins = this.profilePlugins.filter((p) => this.checkedPlugins[p.id]);
    const selectedThemes = this.profileThemes.filter((t) => this.checkedThemes[t.name]);
    if (!selectedPlugins.length && !selectedThemes.length) {
      new import_obsidian.Notice("No items selected.");
      return;
    }
    new ConfirmModal(
      this.app,
      `Are you sure you want to uninstall ${selectedPlugins.length} plugin(s) and ${selectedThemes.length} theme(s)? This will delete their files.`,
      () => {
        void this.executeUninstall(selectedPlugins, selectedThemes);
      }
    ).open();
  }
  async executeUninstall(selectedPlugins, selectedThemes) {
    this.installing = true;
    this.btnConfirm.disabled = true;
    this.btnUninstall.disabled = true;
    this.btnUninstall.setText("Uninstalling...");
    this.logEl.setCssStyles({ display: "block" });
    this.logEl.empty();
    this.log = [];
    let success = 0, skip = 0, fail = 0;
    for (const p of selectedPlugins) {
      const id = p.id;
      this.appendLog(`
\u2500\u2500 Uninstalling [Plugin] ${p.name}`);
      const isInstalled = await this.app.vault.adapter.exists((0, import_obsidian.normalizePath)(`${this.app.vault.configDir}/plugins/${id}/main.js`));
      if (!isInstalled) {
        this.appendLog(`  \u23ED Not installed, skipping.`);
        skip++;
        continue;
      }
      try {
        const appWithPlugins = this.app;
        if (appWithPlugins.plugins && typeof appWithPlugins.plugins.uninstallPlugin === "function") {
          this.appendLog(`  Removing plugin files and disabling...`);
          console.warn(`[S-Restore Profile] Using internal API 'uninstallPlugin' for ${id}`);
          await appWithPlugins.plugins.uninstallPlugin(id);
        } else {
          this.appendLog(`  Removing plugin folder...`);
          await this.app.vault.adapter.rmdir((0, import_obsidian.normalizePath)(`${this.app.vault.configDir}/plugins/${id}`), true);
        }
        this.appendLog(`  \u2705 Uninstalled successfully.`);
        success++;
      } catch (e) {
        this.appendLog(`  \u274C Failed: ${e.message}`);
        fail++;
      }
    }
    for (const t of selectedThemes) {
      const name = t.name;
      this.appendLog(`
\u2500\u2500 Uninstalling [Theme] ${name}`);
      const dir = (0, import_obsidian.normalizePath)(`${this.app.vault.configDir}/themes/${name}`);
      const isInstalled = await this.app.vault.adapter.exists(dir);
      if (!isInstalled) {
        this.appendLog(`  \u23ED Not installed, skipping.`);
        skip++;
        continue;
      }
      try {
        this.appendLog(`  Removing theme folder...`);
        await this.app.vault.adapter.rmdir(dir, true);
        const apPath = (0, import_obsidian.normalizePath)(this.app.vault.configDir + "/appearance.json");
        let apData = {};
        try {
          const apRaw = await this.app.vault.adapter.read(apPath);
          apData = JSON.parse(apRaw);
          if (apData.cssTheme === name) {
            apData.cssTheme = "";
            await this.app.vault.adapter.write(apPath, JSON.stringify(apData, null, 2));
            this.appendLog(`  \u2705 Removed from active theme.`);
          }
        } catch (e) {
        }
        this.appendLog(`  \u2705 Uninstalled successfully.`);
        success++;
      } catch (e) {
        this.appendLog(`  \u274C Failed: ${e.message}`);
        fail++;
      }
    }
    this.appendLog(`
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550`);
    this.appendLog(`\u2705 Uninstalled : ${success}`);
    this.appendLog(`\u23ED Skipped     : ${skip}`);
    this.appendLog(`\u274C Failed      : ${fail}`);
    this.installing = false;
    this.btnConfirm.disabled = false;
    this.btnUninstall.disabled = false;
    this.btnUninstall.setText("Uninstall selected");
    this.refreshUI();
  }
  refreshUI() {
    this.contentEl.empty();
    this.contentEl.createEl("h2", { text: "S-Restore Profile" });
    this.renderList(this.contentEl);
    if (this.log.length > 0) {
      this.logEl.setCssStyles({ display: "block" });
      this.logEl.empty();
      this.log.forEach((msg) => {
        this.logEl.createEl("div", { text: msg });
      });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var S_DOWNLOAD_ICON = `
<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  <polyline points="7 11 12 16 17 11" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M12 3c-1.8 0-3 1-3 2.5s1.2 2 3 2.5 3 1.2 3 2.5-1.2 2.5-3 4" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
var SRestoreProfile = class extends import_obsidian.Plugin {
  async onload() {
    (0, import_obsidian.addIcon)("s-restore-profile-icon", S_DOWNLOAD_ICON);
    this.addCommand({
      id: "open-profile-manager",
      name: "Open profile manager",
      callback: () => new ReinstallerModal(this.app).open()
    });
    this.addRibbonIcon("s-restore-profile-icon", "S-Restore Profile", () => {
      new ReinstallerModal(this.app).open();
    });
  }
};

/* nosourcemap */